#!/bin/sh /etc/rc.common
START=99
STOP=99

start() {
	. /etc/functions.sh
	config_load truewifi
	local disabled
	config_get_bool disabled setting disabled
	[ $disabled -eq 0 ] || return 1
		/usr/bin/truewifi
}

stop() {
	killall truewifi
}
